server:
  port: 38080
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connection-timeout: 5000  # 5초
      request-read-timeout: 5000   # 5초
      fail-fast: true   # 운영환경은 true로 설정
      retry:
        max-attempts: 6
        initial-interval: 1000  # 1초
        max-interval: 2000  # 2초
        multiplier: 1.1

management:
  endpoints:
    web:
      exposure:
        include: refresh
polar:
  greeting: Welcome to the local book catalog!