apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
  labels:
    app: catalog-service
data:
  application.yml: |
    polar:
      greeting: Welcome to the book catalog from Kubernetes!
    spring:
      datasource:
        url: jdbc:mariadb://192.168.56.40:3306/polardb_catalog
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://192.168.56.30:30880/realms/PolarBookshop
